dist:
  trusty

language:
  java

jdk:
  - oraclejdk8

node_js:
  - 10

cache:
  directories:
    - $HOME/.m2

before_install:
  - nvm install 10

before_script:
  - npm install --prefix client/
  - node -v

script:
  - mvn clean test jacoco:report coveralls:report
  - npm run build --prefix client/