server:
  port: 5000

spring:
  profiles:
    active: @spring.profiles.active@

  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 15MB

  datasource:
    url: jdbc:mysql://aaj7867w1r4cg.cbrahwcrixlg.eu-west-2.rds.amazonaws.com:3306/ebdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: # <username>
    password: # <password>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    jwt-secret:
      ${random.uuid}
    oauth2:
      client:
        registration:
          google:
            client-id: 80984151153-9f91p0h7vtpivo52535okhirjrdom0ld.apps.googleusercontent.com # <client-id>
            client-secret: T2uF0otx0tP-wPnqStyfRrDa                                            # <client-secret>

  mail:
    host: smtp.gmail.com
    port: 587
    username: growingnetwork.service@gmail.com
    password: # <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
amazonProperties:
  endpointUrl: https://s3.eu-west-2.amazonaws.com
  bucketName: elasticbeanstalk-eu-west-2-160059151014 # <bucketName>